---
# tasks file for ignite
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.suoders
  ansible.builtin.include_role:
    name: andrewrothstein.sudoers
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jre
- name: Looking for install at {{ ignite_exe }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ ignite_exe }}'
  register: ignite_binary
- name: Downloading and installing ignite
  when: not ignite_binary.stat.exists
  block:
    - name: Downloading {{ ignite_url }} to {{ ignite_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ ignite_url }}'
        dest: '{{ ignite_tmp_archive }}'
        mode: '644'
        checksum: '{{ ignite_checksum }}'
    - name: Unarchiving {{ ignite_tmp_archive }} to {{ ignite_parent_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ ignite_tmp_archive }}'
        dest: '{{ ignite_parent_install_dir }}'
        creates: '{{ ignite_exe }}'
  always:
    - name: Rm {{ ignite_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ ignite_tmp_archive }}'
        state: absent
- name: Linking {{ ignite_link_dir }} to {{ ignite_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ ignite_install_dir }}'
    dest: '{{ ignite_link_dir }}'
    state: link
- name: Install ignite config
  become: true
  become_user: root
  with_items:
    - f: default-config.xml
      d: '{{ ignite_install_dir }}/config'
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'

- name: Configuring with {{ ignite_supervisor | default("systemd") }}
  ansible.builtin.include_tasks: '{{ ignite_supervisor | default("systemd") }}.yml'
