---
- name: Installing systemd servicer
  ansible.builtin.include_role:
    name: andrewrothstein.systemd_service
  vars:
    systemd_service_activate: '{{ ignite_activate }}'
    systemd_service_def:
      activate: '{{ ignite_activate }}'
      enabled: '{{ ignite_enabled }}'
      description: Apache Ignite Server
      after:
        - network.target
      name: ignite
      account:
        enabled: true
        user: ignite
        group: ignite
      env:
        dir: /etc/ignite
        filename: env
        addl_files:
          - '-/usr/local/openjdk-jre/openjdk.env'
      ty: simple
      working_directory: '{{ ignite_link_dir }}'
      start:
        exe: '{{ ignite_link_dir }}/bin/ignite.sh'
      restart:
        policy: on-failure
      wanted_by:
        - multi-user.target
