---
- name: andrewrothstein.unarchivedeps
  version: 3.0.2
- name: andrewrothstein.temurin
  version: 2.0.0
- name: andrewrothstein.sudoers
  version: v1.2.3
- name: andrewrothstein.systemd_service
  version: v3.2.2
